spring:
  application:
    name: coverletter-spring-project
  datasource:
#    url: jdbc:h2:tcp://localhost/~/test # 웹 UI로 데이터 베이스 다루고 싶으면 이거로 설정하고, localhost:8082 로 접속 GOGOGO.
    url: jdbc:h2:mem:test # 커밋 할 때는 이거로 설정.
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create # 이 옵션은 애플리케이션 실행 시점에 테이블을 drop 하고, 다시 생성한다.
    properties:
      hibernate:
        # show_sql: true # `System.out` 에 하이버네이트 실행 SQL을 남긴다.
        format_sql: true
logging.level:
  org.hibernate.SQL: debug # logger를 통해 하이버네이트 실행 SQL을 남긴다.
  org.hibernate.orm.jdbc.bind: trace

