name: DEV BRANCH TEST

on:
  # push:
    # branches:
    #   - dev
  pull_request:
    branches:
      - dev
# -
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code from repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # - name: Build with Gradle
    #   run: ./gradlew build

    - name: Run tests
      run: ./gradlew test
